### ISSUE TITLE
Question about Urock wind speeds

### ISSUE THREAD

**Issue by lgzdbf** [UMEP-dev/UMEP#752]
Hi,

I am currently analyzing each Urock output for every hour studied. On some pixels, I am observing rather high values compared to the initial wind speed (double the initial wind speed value in the example) provided in the forcing data.

Do you think this is normal?

I am attaching a case for a specific day and tile. Let me know if you would like more examples.

Also, I am not sure if this observation qualifies as an "issue". Feel free to tell me if you would prefer that I open it as a discussion instead.

Thanks in advance, 

[c-408_grenoble.zip](https://github.com/user-attachments/files/20756367/c-408_grenoble.zip)

**Comment by j3r3m1** [comment]
I would not be surprise that the wind speed can greatly increase in some areas. However, the location of your high wind speed is probably not realistic. However I do not think it is a bug but more the result of the use of Röckle based models which are not (yet ;-)) perfect for all situations. I suppose you do not have the vector output ? It is often a good idea to keep it to better interpret the results.

**Comment by lgzdbf** [comment]
Thanks for your answer. If you want I have Rockle zones associated data. Let me know if it is vector data you are talking about.

[Rockle_zones_c-408.zip](https://github.com/user-attachments/files/21680250/Rockle_zones_c-408.zip)

**Comment by j3r3m1** [comment]
No I am talking about the output wind saved as a vector file. Having the wind field with wind direction is easier to interpret what we can observe as wind speed.

**Comment by lgzdbf** [comment]
Ok, I see, maybe that ? 

[urock_output.zip](https://github.com/user-attachments/files/21680462/urock_output.zip)

**Comment by j3r3m1** [comment]
Yes this is it. The acceleration is due to the strange building shape. All the wind coming from the north part of the cavity zone is ending in the small zone located between the building and the vegetation, leading to a quite high increase of the wind speed.

<img width="590" height="565" alt="Image" src="https://github.com/user-attachments/assets/4efb180f-09b0-45e1-bc28-ab8715b0a030" />

I need to check the initialization of the wind because it seems that the resulting wind is quite strange around the complex building geometry.

**Comment by j3r3m1** [comment]
Indeed bug in the vegetation located in built zone: the wind is set to 0 instead of being only deccelerated. I need to investigate why this behavior is now happening...

<img width="590" height="565" alt="Image" src="https://github.com/user-attachments/assets/1f4fdf09-154d-4f0a-9ba9-72a408ead14a" />

**Comment by j3r3m1** [comment]
OK no problem the reason is simple. When z<z0 the wind speed of points located in vegetation polygons is set to 0. For this zone and wind direction, z0 = 1.98. The previous image is for z=1.5m.
Above 1.98 m the problem disappear (below is for 5m height).

<img width="590" height="565" alt="Image" src="https://github.com/user-attachments/assets/3f9a7447-ac32-4788-af80-c0c5ac0c434d" />

**Comment by lgzdbf** [comment]
Okay, thank you for your feedback; so ultimately, is this wind speed of around 8 m/s consistent?

**Comment by j3r3m1** [comment]
In summary:
- there is no bug since the algorithm does what it is supposed to do when initializing the wind speed
- However, having wind speed equal to 0 in some area results in a quite high wind speed after mass balance (and in a direction which is far from obvious in my opinion...) --> it affects the wind speed in some area nearby (your 8 m/s is part of this area)
==> I have updated the code in order to limit this phenomenon (https://github.com/UMEP-dev/UMEP-processing/commit/58d4c77485c6bda4b6daf4bbcbba9dfabcee4b23). The wind in this area is now 6 m/s. The high value is still due to the complex geometry associated to the Röckle model type. I would not expect the wind being that high at this location. However, difficult to be more objective except using CFD simulations.

With the new version, at 1.5 m/s:
Initialisation:
<img width="590" height="565" alt="Image" src="https://github.com/user-attachments/assets/ce7b7876-51e8-48de-ae7f-a6da56022edb" />

Resulting wind field after mass-balance:
<img width="590" height="565" alt="Image" src="https://github.com/user-attachments/assets/3d01e7cb-0e8f-4802-b5ee-ca452bedaad8" />

**Comment by lgzdbf** [comment]
Great, thank you very much, that is very clear! Thanks again for your help.

**Comment by lgzdbf** [comment]
Hi @j3r3m1, I reran Urock for this cell-day with the 2.2.5 version of Urock, but I am still getting 8 m/s instead of the 6 m/s you mentioned. Is that normal, or did I miss a step?

**Comment by j3r3m1** [comment]
The result I obtain are for 3m horizontal and vertical resolution while it seems you are using 1 m. In general it does not modify a lot the results but for some specific pixels it seems quite important.
Here is what I have obtained for the 3 m resolution with version 2.2.5 at z = 1.5 m.

[urock_outputWS.tif](https://github.com/user-attachments/files/22979290/urock_outputWS.tif)

Same for you ?

**Comment by lgzdbf** [comment]
Thanks for your answer. With your settings and without my output template, I have de same result!

**Comment by j3r3m1** [comment]
Is the difference due to the horizontal resolution or the output template ? Hopefully the horizontal resolution =)

**Comment by lgzdbf** [comment]
Hard to say, because I did three tests and got different results each time ;-) :

1.  3 m resolution without template, max = 6.75 ms (same result as you)
2. 1 m resolution without template, max = 4.72 ms
3. 3 m resolution but with a 1 m template, max = 8.4 ms

**Comment by j3r3m1** [comment]
There is something to investigate between 2 and 3. Maybe it is normal but I have to check where does come this difference from

**Comment by j3r3m1** [comment]
I think that the maximum of your case 2 is 10.85 m/s instead of the 4.72 m/s you mentionned. [Here is my data](https://github.com/user-attachments/files/23019957/urock_outputWS.tif) and I suppose you get the same. QGIS is supposed to automatically identifies min and max and adapt the scale but sometimes it does not work properly. If you calculate the max of your raster you will get 10.85 m/s instead of the 4.72 m/s displayed.

So the results are (I have added a case 4):
Case 1:  3 m resolution without template, max = 6.75 ms (calculations are performed at 3 m resolution and kept as this resolution)
Case 2: 1 m resolution without template, max = 10.85 m/s (Calculations are performed at 1 m res and kept at this resolution)
Case 3: 3 m resolution but with a 1 m template, max = 8.4 ms (Calculations are performed at 3 m resolution and interpolated at 1 m resolution)
Case 4: 1 m resolution with the template, max = 10.24 m/s (Calculations are performed at 1 m res and kept at this resolution)

If I resample the four cases to the same 3 m resolution, there is little (relative) difference between the cases:
Case 1: 6.8 m/s
Case 2: 8.1 m/s (second highest value in the zone being 6.9 m/s)
Case 3: 6.3 m/s
Case 4: 7.5 m/s

Cases 1 and 3 and cases 2 and 4 being calculated at the same resolution, these are the ones I expect to have the closest values, which is the case both at 1 and 3 m resolution. So I suppose everything works fine.

**Comment by lgzdbf** [comment]
Yes, indeed, I forgot the min–max handling in QGIS . So, in all four cases, I get the same values as you, with only a few hundredths of a difference in some cases, but nothing wrong. Top if everything is working well ! :)
